### ISSUE TITLE
执行 npm run dev时,缺失DemoSTLLoader...

### ISSUE THREAD

**Issue by mengxin-FE** [deepkolos/three-platformize-demo-wechat#2]
执行 npm run dev时, 报错：miniprogram/pages/index/index.ts 缺失DemoSTLLoader，DemoTTFLoader，DemoBVHLoader, DemoFBXLoader, DemoLWOLoader, DemoMTLLoader, DemoColladaLoader, DemoMeshQuantization

three-platformize-demo/src/index.ts中未导出上述module

**Comment by mengxin-FE** [comment]
![微信截图_20210219101004](https://user-images.githubusercontent.com/14139852/108447364-b1e46f00-729a-11eb-8b1a-569ed8d9b552.png)

**Comment by mengxin-FE** [comment]
大佬 包里面缺了好几个ts文件啊

**Comment by deepkolos** [comment]
缺demo文件，我发一下包就好了， 1.0.5，如果不是需要修改，直接改appid打开是可以跑起来的

**Comment by mengxin-FE** [comment]
> 缺demo文件，我发一下包就好了， 1.0.5，如果不是需要修改，直接改appid打开是可以跑起来的

明白 等您的包 感谢感谢

**Comment by deepkolos** [comment]
已经发包了，其实index.ts去掉demo的应用也能跑，包更新可能没包快
