### ISSUE TITLE
真机所有例子都不显示，vConsole无任何错误

### ISSUE THREAD

**Issue by jie** [deepkolos/three-platformize-demo-wechat#3]
所有模型在开发工具里都正常，真机都不显示
已打开vConsole，已设置不校验域名和证书

![IMG_2577](https://user-images.githubusercontent.com/8618/112100793-a01b2200-8be0-11eb-862b-1d59f2fa4e06.PNG)
![IMG_2578](https://user-images.githubusercontent.com/8618/112100802-a1e4e580-8be0-11eb-889a-c6a182e9bfd3.PNG)
![IMG_2579](https://user-images.githubusercontent.com/8618/112100803-a3161280-8be0-11eb-965a-48b5f59a1077.PNG)

**Comment by deepkolos** [comment]
示例是个按钮，点击一下会弹出来

**Comment by jie** [comment]
> 示例是个按钮，点击一下会弹出来

后面两张图是点了菜单里的模型以后的页面，你可以看到顶部那个菜单已经不见了

**Comment by deepkolos** [comment]
是iphone几呢，我这边手头只有iphone7的测试机，晚点我测测看看能不能复现

**Comment by jie** [comment]
@deepkolos iPhoneX

**Comment by xzq2325** [comment]
我用iPhoneX测试也是这样的。不过用P30的话打开调试模式才可以显示模型，不打开的话也不行。

**Comment by deepkolos** [comment]
@xzq2325 对的，备注里提到了，需要开调试模式，不校验域名

**Comment by deepkolos** [comment]
这边测试正常，那就先close了

https://user-images.githubusercontent.com/12824616/114516574-1ce56d00-9c70-11eb-9b90-b4746b4acfef.mp4
